// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zztzymixunkchttdhsqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6dHp5bWl4dW5rY2h0dGRoc3FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MDMyNjksImV4cCI6MjA3Mjk3OTI2OX0.znKO-E7ObxbmlEm-II62-PYoT98dQ6UMNfljGMtViC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});